name: Build do Projeto

on:
  push:
    branches:
      - main  # Altere para a branch que deseja monitorar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes
        run: npm test

      - name: Build do projeto
        run: npm run build

      - name: Armazenar artefatos do build
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: .next  # Pasta onde o Next.js gera o build
